name: Daily AoC 2025 Solve

on:
  schedule:
    # Every day at 05:00 UTC = 06:00 or 07:00 in Europe/Warsaw
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      AOC_SESSION: ${{ secrets.AOC_SESSION }}
      
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install requests google-genai

      - name: Run script with retries until PASSED
        run: |
          set -e

          MAX_RETRIES=10
          ATTEMPT=1

          while [ $ATTEMPT -le $MAX_RETRIES ]; do
            echo "=== Attempt $ATTEMPT/$MAX_RETRIES ==="

            CURRENT_DAY=$(TZ="Europe/Warsaw" date +'%d')
            echo "Using CURRENT_DAY=$CURRENT_DAY"

            python aoc25.py "$CURRENT_DAY"

            if [ -f result.txt ]; then
             
              if grep -q "Already Solved" result.txt; then
                echo "Already passed!"
                exit 0
              fi
            
              if grep -q "star:" result.txt; then
                echo "'star:' found in result.txt (run passed)"

                if grep -q "star: 2" result.txt; then
                  echo "PASSED: star 2 found in result.txt ✅"
                  exit 0
                else
                  echo "'star:' present but not 'star: 2' (so we passed first lvl) resetting attempts"
                  ATTEMPT=0 # we later add one so that's why we put here 0
                fi
              else
                echo "'star' not found in result.txt ❌"
              fi
            fi

            ATTEMPT=$((ATTEMPT + 1))
            if [ $ATTEMPT -le $MAX_RETRIES ]; then
              echo "Retrying..."
              sleep 5
            fi
          done

          echo "Failed after $MAX_RETRIES attempts (no PASSED in result.txt)."
          exit 1